### ISSUE TITLE
哈哈

### ISSUE THREAD

**Issue by dylanzan** [TGSAN/FuckXixunyun#1]
之前我用shell也写了一个，习讯云签到工具。

**Comment by dylanzan** [comment]
https://github.com/zanshichun/MyScript/blob/master/xxy_sgin.sh
没有你的功能多，我当时做的是批量签到的，哈哈哈

**Comment by TGSAN** [comment]
> https://github.com/zanshichun/MyScript/blob/master/xxy_sgin.sh
> 没有你的功能多，我当时做的是批量签到的，哈哈哈

主要是这辣鸡习讯云不支持Android9很难受

**Comment by TGSAN** [comment]
（好了不皮了）
