### ISSUE TITLE
发现一个项目好像用了你的代码

### ISSUE THREAD

**Issue by starlight196** [TGSAN/FuckXixunyun#4]
https://github.com/kuilei0926/xixunyun

**Comment by starlight196** [comment]
![image](https://user-images.githubusercontent.com/22676687/165496692-16d39125-6a4a-4e45-9e17-92a2d12ade66.png)

**Comment by starlight196** [comment]
那独特的颜文字也有

**Comment by TGSAN** [comment]
> 那独特的颜文字也有

这个项目随手写的，刚才看了下那个项目，看上去好像注释和我写的一样，暂时不管了（
